### ISSUE TITLE
Vagrant or docker for Linux dev enviroment? 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/vagrant#5]
I've never used Vagarant, [reading this](http://stackoverflow.com/questions/16647069/should-i-use-vagrant-or-docker-for-creating-an-isolated-environment), do you think Docker would be a better solution for someone (like myself) who is already running Linux Ubuntu without any VM's installed to setup a dev enviroment?

Either way, I love the idea of a dedicated replicable dev environment that's easy to setup for Emoncms (ideally with a couple of years of feed test data, that I'm happy to provide). Having multiple options for dev environment to suite different platforms is also a good idea. 

Thanks a lot for your contribution 👍

**Comment by inverse** [comment]
Docker does sound like a more lightweight solution, especially if you're running *nix since on windows I believe it's all encapsulated in a VM (but don't quote me on that).

As for the test data - that'll surely be a good thing to have in place - even just like in the other thread on this some cron pushing data in to simulate real input. Will def need to investigate this set this up!
